name: CI/CD Pipeline

# Trigger the workflow on push or pull request events
on:
  push:
    branches: 
      - main  # This will trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # This will trigger the workflow on pull requests targeting the main branch

jobs:
  # Job to run tests
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Or specify your desired version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install your dependencies

      - name: Run tests
        run: |
          pytest  # You can change this command to whatever testing framework you're using, like `pytest`, `unittest`, etc.

  # Job for deployment (this only runs if tests pass)
  deploy:
    runs-on: ubuntu-latest
    needs: test  # This means the deploy job will only run if the "test" job succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to production (Example)
        run: |
          # Your deployment scripts here (could be an SSH command, or using AWS CLI, etc.)
          echo "Deploying to production..."

